import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  formField: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 8,
    shadowColor: '#02217C',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  fieldRow: {
    flexDirection: 'row',
    gap: 12,
  },
  leftSection: {
    width: 130,
  },
  middleSection: {
    flex: 1,
  },
  rightSection: {
    width: 110,
    alignItems: 'flex-end',
  },
  labelPill: {
    backgroundColor: '#DBEAFE',
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#93C5FD',
  },
  labelText: {
    color: '#02217C',
    fontWeight: '700',
    fontSize: 11,
    textAlign: 'center',
  },
remarksLabel: {
  fontSize: 9,
  fontWeight: '600',
  color: '#475569',
  lineHeight: 12,
},
  remarksContainer: {
  position: 'relative',
},
remarksLabelWrapper: {
  position: 'absolute',
  left: -108, 
  top: 8,
  width: 100,
  zIndex: 1,
},

  input: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 11,
    marginBottom: 6,
    color: '#1E293B',
  },
  textArea: {
    minHeight: 50,
    textAlignVertical: 'top',
  },
  subFieldRow: {
    marginBottom: 6,
  },
  subFieldLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  bullet: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#02217C',
    marginRight: 6,
  },
  subFieldLabelText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#475569',
  },
  radioLabel: {
    fontSize: 11,
    color: '#1E293B',
    marginBottom: 8,
    fontWeight: '600',
  },
  radioRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor:'#02217C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#02217C',
  },
  radioText: {
    fontSize: 11,
    color: '#1E293B',
    fontWeight: '500',
  },
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#02217C',
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginTop: 10,
    backgroundColor: '#EFF6FF',
    borderRadius: 6,
  },
  uploadText: {
    marginLeft: 4,
    fontSize: 10,
    color: '#02217C',
    fontWeight: '600',
  },
  imagePreviewContainer: {
    marginTop: 8,
    position: 'relative',
    width: 100,
    height: 75,
  },
  imagePreview: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  removeImageButton: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#DC2626',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#DC2626',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
});