import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  formField: {
    position: 'relative', // Add this line
    backgroundColor: "#FFFFFF",
    paddingVertical: 20,
    paddingHorizontal: 20,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    ...Platform.select({
      ios: {
        shadowColor: "#1E3A8A",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  fieldRow: {
    flexDirection: "column",
    gap: 16,
  },
  leftSection: {
    width: "100%",
  },
  middleSection: {
    flex: 1,
    width: "100%",
  },
  rightSection: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  labelPill: {
    backgroundColor: "#DBEAFE",
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: "#93C5FD",
    alignSelf: "flex-start",
    ...Platform.select({
      ios: {
        shadowColor: "#1E3A8A",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 3,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  labelText: {
    color: "#1E3A8A",
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 0.2,
    lineHeight: 19,
  },
  remarksLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#475569",
    lineHeight: 17,
    letterSpacing: 0.2,
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#CBD5E1",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 13,
    marginBottom: 10,
    color: "#1E293B",
    lineHeight: 20,
    minHeight: 50,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: "top",
    paddingTop: 14,
  },
  radioLabel: {
    fontSize: 14,
    color: "#1E293B",
    marginBottom: 0,
    marginRight: 16,
    fontWeight: "600",
    letterSpacing: 0.2,
    lineHeight: 19,
  },
  radioRow: {
    flexDirection: "row",
    gap: 16,
    alignItems: "center",
  },
  radioOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "#1E3A8A",
    alignItems: "center",
    justifyContent: "center",
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#1E3A8A",
  },
  radioText: {
    fontSize: 13,
    color: "#1E293B",
    fontWeight: "500",
    letterSpacing: 0.1,
    lineHeight: 18,
  },
  deleteButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: '#FEE2E2',
    borderRadius: 16,
    padding: 6,
    borderWidth: 1,
    borderColor: '#DC2626',
    zIndex: 10,
    elevation: 2,
  },
  addButton: {
    backgroundColor: "#EFF6FF",
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#93C5FD",
    flexDirection: "row",
    gap: 8,
    ...Platform.select({
      ios: {
        shadowColor: "#1E3A8A",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  addButtonText: {
    fontSize: 14,
    color: "#1E3A8A",
    fontWeight: "700",
    letterSpacing: 0.3,
    lineHeight: 19,
  },
});