import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  additionalContainer: {
    marginTop: 24,
    paddingTop: 24,
    borderTopWidth: 2,
    borderTopColor: "#BFDBFE",
    position: "relative",
  },
  deleteButton: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "#FEE2E2",
    borderRadius: 16,
    padding: 6,
    borderWidth: 1,
    borderColor: "#DC2626",
    zIndex: 10,
    elevation: 2,
  },

  parameterHeader: {
    marginBottom: 8,
  },
  parameterLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#02217C",
  },
  parameterInput: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    marginBottom: 16,
    borderRadius: 6,
    color: "#1E293B",
  },
  mmtSubSection: {
    marginTop: 16,
    marginBottom: 16,
    paddingLeft: 12,
    borderLeftWidth: 3,
    borderLeftColor: "#02217C",
  },
  mmtTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#02217C",
    marginBottom: 8,
  },
  remarksLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#334155",
    marginBottom: 6,
    marginTop: 12,
  },
  remarksInput: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    marginBottom: 8,
    borderRadius: 6,
    color: "#1E293B",
    minHeight: 80,
    textAlignVertical: "top",
  },
});
