import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  resultLabelItalic: {
    fontSize: 13,
    fontWeight: '600',
    fontStyle: 'italic',
    color: '#02217C',
    marginRight: 6,
  },
  resultLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1E293B',
    marginRight: 8,
  },
  monthSelector: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 140,
  },
  monthText: {
    fontSize: 12,
    color: '#1E293B',
    fontWeight: '500',
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    width: '80%',
    maxHeight: '70%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#02217C',
  },
  monthList: {
    maxHeight: 400,
  },
  monthOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  monthOptionSelected: {
    backgroundColor: '#EFF6FF',
  },
  monthOptionText: {
    fontSize: 14,
    color: '#1E293B',
    fontWeight: '500',
  },
  monthOptionTextSelected: {
    color: '#02217C',
    fontWeight: '700',
  },
  tssContainer: {
    backgroundColor: '#EFF6FF',
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  tssName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#02217C',
  },
  tssInputs: {
    flexDirection: 'row',
    gap: 12,
  },
  tssInputGroup: {
    flex: 1,
  },
  tssInputLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 6,
  },
  tssHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  tssNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tssCheckbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: '#02217C',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  tssCheckboxChecked: {
    backgroundColor: '#EFF6FF',
  },
  deleteTSSButton: {
    backgroundColor: '#FEE2E2',
    borderRadius: 16,
    padding: 6,
    borderWidth: 1,
    borderColor: '#DC2626',
  },
  tssInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
    borderRadius: 6,
    color: '#1E293B',
  },
  tssInputDisabled: {
    backgroundColor: '#F1F5F9',
    color: '#94A3B8',
    borderColor: '#E2E8F0',
  },
  addTSSButton: {
    backgroundColor: '#EFF6FF',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 16,
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  addTSSText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#02217C',
  },
  bullet: {
  width: 6,
  height: 6,
  borderRadius: 3,
  backgroundColor: '#02217C',
  marginRight: 8,
},
});