import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    marginBottom: 20,
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  containerDisabled: {
    backgroundColor: '#FAFAFA',
    opacity: 0.7,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  numberBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#DBEAFE',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    marginTop: 24,
    borderWidth: 1,
    borderColor: '#93C5FD',
  },
  numberBadgeDisabled: {
    backgroundColor: '#F1F5F9',
    borderColor: '#E2E8F0',
  },
  number: {
    fontSize: 13,
    fontWeight: '700',
    color: '#02217C',
  },
  inputsRow: {
    flex: 1,
    flexDirection: 'row',
    gap: 12,
  },
  inputWrapper: {
    flex: 1,
  },
  label: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
    textAlign: 'center',
    color: '#475569',
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 12,
    minHeight: 45,
    textAlignVertical: 'top',
    color: '#1E293B',
  },
  inputDisabled: {
    backgroundColor: '#F1F5F9',
    borderColor: '#E2E8F0',
    color: '#94A3B8',
  },
  effectiveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingLeft: 40,
    backgroundColor: '#EFF6FF',
    paddingVertical: 8,
    paddingRight: 12,
    borderRadius: 6,
  },
  effectiveRowDisabled: {
    backgroundColor: '#F8FAFC',
  },
  effectiveLabel: {
    fontSize: 13,
    fontWeight: '600',
    marginRight: 16,
    color: '#1E293B',
  },
  radioGroup: {
    flexDirection: 'row',
    gap: 16,
  },
  recommendationsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingLeft: 40,
  },
  recommendationsLabel: {
    fontSize: 13,
    fontWeight: '600',
    marginRight: 12,
    minWidth: 120,
    color: '#1E293B',
  },
  recommendationsInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 12,
    minHeight: 45,
    textAlignVertical: 'top',
    color: '#1E293B',
  },
  textDisabled: {
    color: '#94A3B8',
  },
});