import { StyleSheet } from 'react-native';

export const parameterFormStyles = StyleSheet.create({
  container: {
    position: 'relative',
    paddingTop: 10, // Add padding to accommodate the delete button
  },
  deleteButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#FEE2E2',
    borderRadius: 16,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#DC2626',
    zIndex: 10,
     padding: 6,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  parameterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  parameterLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#02217C',
  },
  naContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
  },
  naCheckbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: '#02217C',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    backgroundColor: '#FFFFFF',
  },
  naCheckboxChecked: {
    backgroundColor: '#EFF6FF',
  },
  naLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
  },
  parameterInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 13,
    marginBottom: 20,
    color: '#1E293B',
  },
  disabledInput: {
    backgroundColor: '#F1F5F9',
    color: '#94A3B8',
    opacity: 0.6,
  },
  disabledSection: {
    opacity: 0.5,
  },
  resultsContainer: {
    backgroundColor: '#EFF6FF',
    padding: 16,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  resultsTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#02217C',
    marginBottom: 16,
  },
  resultsGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  resultColumn: {
    flex: 1,
  },
  columnHeaderContainer: {
    backgroundColor: '#DBEAFE',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#93C5FD',
  },
  columnHeader: {
    fontSize: 13,
    fontWeight: '700',
    color: '#02217C',
    textAlign: 'center',
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#475569',
    marginTop: 8,
    marginBottom: 6,
  },
  resultInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: '#1E293B',
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: 8,
    marginTop: 8,
  },
  subLabel: {
    fontSize: 12,
    fontWeight: '400',
    color: '#64748B',
  },
  eqplSection: {
    backgroundColor: '#F8FAFC',
    padding: 14,
    borderRadius: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  eqplTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#02217C',
    marginBottom: 12,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 13,
    marginBottom: 12,
    color: '#1E293B',
  },
  textInput: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 13,
    minHeight: 80,
    textAlignVertical: 'top',
    marginBottom: 16,
    color: '#1E293B',
  },
});

export const locationCheckboxRowStyles = StyleSheet.create({
  formRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: '#02217C',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginRight: 12,
  },
  checkboxSelected: {
    backgroundColor: '#EFF6FF',
  },
  formLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#1E293B',
    width: 100,
  },
  formInput: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    marginLeft: 8,
    color: '#1E293B',
  },
  formInputDisabled: {
    backgroundColor: '#F1F5F9',
    color: '#94A3B8',
    opacity: 0.6,
  },
});

export const checkboxFieldStyles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 8,
  },
  checkbox: {
    borderWidth: 2,
    borderColor: '#02217C',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: '#EFF6FF',
    borderColor: '#02217C',
  },
  label: {
    fontSize: 14,
    color: '#1E293B',
    fontWeight: '500',
  },
});

export const formInputFieldStyles = StyleSheet.create({
  container: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: 8,
  },
  subLabel: {
    fontSize: 12,
    fontWeight: '400',
    color: '#64748B',
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 13,
    color: '#1E293B',
  },
  multilineInput: {
    minHeight: 80,
  },
});

// styles file - update sectionHeaderStyles
export const sectionHeaderStyles = StyleSheet.create({
  container: {
    backgroundColor: "#EFF6FF",
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 16,
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    borderRadius: 10,
    gap: 12,
    shadowColor: "#02217C",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  numberBadge: {
    backgroundColor: "#02217C",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    minWidth: 40,
    alignItems: "center",
  },
  number: {
    fontSize: 13,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  title: {
    fontSize: 14,
    fontWeight: "600",
    color: "#02217C",
    flex: 1,
  },
});